INSERT INTO TBL_SELLERS (NAME,SALARY,BONUS,GENDER) VALUES ('JULIO',2500,300,1);
INSERT INTO TBL_SELLERS (NAME,SALARY,BONUS,GENDER) VALUES ('AMANDA',2700,250,2);
INSERT INTO TBL_SELLERS (NAME,SALARY,BONUS,GENDER) VALUES ('LARISSA',2400,600,2);
INSERT INTO TBL_SELLERS (NAME,SALARY,BONUS,GENDER) VALUES ('GABRIEL',3000,500,1);